- hosts: all
  sudo: yes
  tasks:
    - name: upgrade all packages
      yum: name=* state=latest

    - name: install the current apache
      yum: name=httpd state=latest

    - name: Basic hello page
      template: src="templates/demo_page.html" dest="/var/www/html/index.html" mode="644"

    - name: Have Apache start on boot
      action: command /sbin/chkconfig httpd on

    - name: Restarting Apache
      service: name=httpd state=restarted
